[alembic]
script_location = alembic
prepend_sys_path = .

sqlalchemy.url = mysql+aiomysql://root:xiaofeng71@127.0.0.1:3306/mooda?charset=utf8mb4

[post_write_hooks]
# 格式化生成的迁移脚本

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = WARN
handlers =
qualname = alembic
